package com.example.composetdaapp.utils

const val EXPAND_ANIMATION_DURATION = 200
const val COLLAPSE_ANIMATION_DURATION = 200
const val FADE_IN_ANIMATION_DURATION = 250
const val FADE_OUT_ANIMATION_DURATION = 200
const val GOOD_TILL_CANCEL = "GTC"
const val ARG_OBJECT = ""
const val LEVELONE_FUTURES = "LEVELONE_FUTURES"
